site_name: Hypercubing
site_url: https://hypercubers.github.io/
docs_dir: docs/
repo_name: Hypercubers/hypercubers.github.io
repo_url: https://github.com/Hypercubers/hypercubers.github.io
edit_uri: blob/main/docs/
nav:
  - Welcome: index.md
  - FAQ: faq.md
  - Software: software.md
  - Puzzles: puzzles.md
  - Methods: methods.md
  - Leaderboards: leaderboards.md
theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.svg
  palette:
    scheme: slate
    primary: purple
    accent: indigo
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hypercubers
    - icon: fontawesome/brands/discord
      link: https://discord.gg/3hVSe8rDKa
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
