site_name: Hypercubing
site_url: https://hypercubing.xyz/
docs_dir: docs/
repo_name: Hypercubers/hypercubing.xyz
repo_url: https://github.com/Hypercubers/hypercubing.xyz
edit_uri: blob/main/docs/
nav:
  - Welcome: index.md
  - FAQ: faq.md
  - Software: software.md
  - Puzzles: puzzles.md
  - Methods: methods.md
  - Leaderboards: leaderboards.md
theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hypercubers
    - icon: fontawesome/brands/discord
      link: https://discord.gg/3hVSe8rDKa
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
